spring:
  config:
    activate:
      on-profile: local
  redis:
    host: ${LOCAL_REDIS_HOST}
    port: ${LOCAL_REDIS_PORT}
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
    freemarker:
      cache: false
  h2:
    console:
      enabled: true
  datasource:
    url: ${LOCAL_DB_URL}
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

---
spring:
  config:
    activate:
      on-profile: dev
  redis:
    host: ${DEV_REDIS_HOST}
    port: ${DEV_REDIS_PORT}
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
    freemarker:
      cache: false
  h2:
    console:
      enabled: true
  datasource:
    url: ${DEV_DB_URL}
    driver-class-name: org.h2.Driver
    username: ${DEV_DB_USER}
    password: ${DEV_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
